// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAZROfkifO_lFx3zFnPOEcWrTSnCtvmCI',
    appId: '1:338717367679:web:988010ed6e4b80f33c8e4a',
    messagingSenderId: '338717367679',
    projectId: 'responsive-design-4332c',
    authDomain: 'responsive-design-4332c.firebaseapp.com',
    storageBucket: 'responsive-design-4332c.firebasestorage.app',
    measurementId: 'G-D6C3V7G2Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8BEod2rCVCKKH1KiUJdkKFYNQrvSNHI',
    appId: '1:338717367679:android:4b61a067b4978d913c8e4a',
    messagingSenderId: '338717367679',
    projectId: 'responsive-design-4332c',
    storageBucket: 'responsive-design-4332c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAep_w_tvi5eEG-rjmfQJYwZJ_CBEB_ck0',
    appId: '1:338717367679:ios:2dfb7a24b2e3fd263c8e4a',
    messagingSenderId: '338717367679',
    projectId: 'responsive-design-4332c',
    storageBucket: 'responsive-design-4332c.firebasestorage.app',
    iosBundleId: 'com.example.responsiveDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAep_w_tvi5eEG-rjmfQJYwZJ_CBEB_ck0',
    appId: '1:338717367679:ios:2dfb7a24b2e3fd263c8e4a',
    messagingSenderId: '338717367679',
    projectId: 'responsive-design-4332c',
    storageBucket: 'responsive-design-4332c.firebasestorage.app',
    iosBundleId: 'com.example.responsiveDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAZROfkifO_lFx3zFnPOEcWrTSnCtvmCI',
    appId: '1:338717367679:web:6a2e2d5968e371533c8e4a',
    messagingSenderId: '338717367679',
    projectId: 'responsive-design-4332c',
    authDomain: 'responsive-design-4332c.firebaseapp.com',
    storageBucket: 'responsive-design-4332c.firebasestorage.app',
    measurementId: 'G-TM56LLXJZ7',
  );
}
